
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - mongo_volume:/data/db
  api:
    image: api
    container_name: api
    depends_on:
      - mongodb
    build: 
      context: server
      dockerfile: ./Dockerfile
    ports:
      - 7005:7005

  ui:
    image: ui
    container_name: ui
    depends_on:
      - api
    build:
      context: ui
      dockerfile: ./Dockerfile
    ports:
      - 2004:2004

volumes:
  mongo_volume: